# -*- coding: utf-8 -*-
{
    'name' : 'E-Contract',
    'version' : '1.0',
    'summary': 'Agreement Contract & Quotation',
    'sequence': 30,
    'description': """
Agreement Contract & Quotation
====================
s    
    """,
    'category': 'Agreement',
    'website': "http://www.yourcompany.com",
    # 'images' : ['images/accounts.jpeg','images/bank_statement.jpeg','images/cash_register.jpeg','images/chart_of_accounts.jpeg','images/customer_invoice.jpeg','images/journal_entries.jpeg'],
    'depends': ['base', 'base_setup', 'mail', 'report', 'web_tip', 'web_planner', 'field_image_preview', 'document','web_widget_digitized_signature','report_custom_filename','web_pdf_preview'],
    'data': [
        'security/security.xml',
        'security/ir.model.access.csv',
        'views/views.xml',
        'views/users_contract.xml',
        'views/sales_contract.xml',
        'views/delegation_contract.xml',
        'views/other_telkomsel_contract.xml',
        'views/merchant_contract.xml',
        'views/ratecard_econtract.xml',
        'report/contract_report.xml',      
        'report/quotation_report.xml',    
        'report/soa_report.xml',    
        'views/conract_econtract.xml',
        'views/quotation_econtract.xml',
        # 'views/soa_contract.xml',
        'views/verification_contract.xml',
        'data/contract/new_contract_action_data.xml',  
        'data/contract/approve_contract_merch_action_data.xml',  
        'data/contract/approve_contract_sales_action_data.xml',  
        'data/contract/final_contract_action_data.xml',  
        'data/quotation/quotation_gm_action_data.xml',  
        'data/quotation/quotation_vp_action_data.xml',  
        'data/quotation/approve_quotation_merchant_action_data.xml',  
        'data/quotation/approve_quotation_sales_action_data.xml',  
        'data/quotation/final_quotation_gm_action_data.xml',  
        'data/quotation/final_quotation_vp_action_data.xml',  
        'data/soa/soa_gm_action_data.xml',  
        'data/soa/soa_vp_action_data.xml',  
        'data/soa/approve_soa_merchant_action_data.xml',  
        'data/soa/approve_soa_sales_action_data.xml',  
        'data/soa/final_soa_gm_action_data.xml',  
        'data/soa/final_soa_vp_action_data.xml',  
        'report/reportcontract/report_new_contract.xml',     
        'report/reportcontract/report_approved_merch_contract.xml',
        'report/reportcontract/report_approved_sales_contract.xml',
        'report/reportcontract/report_final_contract.xml',
        'report/reportquotation/report_new_quotation_gm.xml',     
        'report/reportquotation/report_new_quotation_vp.xml',     
        'report/reportquotation/report_approved_merch_quotation.xml',
        'report/reportquotation/report_approved_sales_quotation.xml',
        'report/reportquotation/report_final_gm_quotation.xml',
        'report/reportquotation/report_final_vp_quotation.xml',
        'report/reportsoa/report_new_soa_gm.xml',     
        'report/reportsoa/report_new_soa_vp.xml',     
        'report/reportsoa/report_approved_merch_soa.xml',
        'report/reportsoa/report_approved_sales_soa.xml',
        'report/reportsoa/report_final_gm_soa.xml',
        'report/reportsoa/report_final_vp_soa.xml',
    ],
    'demo': [
        'demo/demo.xml',
    ],
    'installable': True,
    'application': True,
    'auto_install': False,
}